apiVersion: v1
kind: Service
metadata:
  name: {{.Values.hmsHipomService.front.service.name}}
spec:
  selector:
    app: {{.Values.hmsHipomService.front.service.label}}
  ports:
  - name: http
    port: 80
    targetPort: 8091
  type: ClusterIP